addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.20.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.6.4")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.6")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.6.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.5")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.4")
addSbtPlugin("org.creativescala" %% "creative-scala-theme" % "0.4.5")
